### ISSUE TITLE
Update for jupyter notebook 6.0.0

### ISSUE THREAD

**Issue by jph00** [conda-forge/jupyter-feedstock#9]
@minrk @ocefpaf @xylar jupyter notebook 6.0.0 was just released to pypi. I tried upgrading jupyter notebook via pip into a conda env that had the latest version of all packages, and it works fine. Might be worth updating the conda package?

**Comment by ocefpaf** [comment]
This feedstock is the meta-package. The proper updates are already in PRs like https://github.com/conda-forge/notebook-feedstock/pull/52 and will be available soon.
